language: python
python:
  - 2.7
  - pypy
  - 3.5
  - 3.4
  - 3.3
  - 3.2
  - pypy2
env:
  - MATHICS="v0.9"
  - MATHICS="master"
matrix:
  allow_failures:
    - python: 3.2
    - python: pypy2
    - env: MATHICS="v0.9"
before_install:
  - pip install jupyter_kernel_test
  - pip install unittest2
  - pip install git+https://github.com/mathics/mathics.git@master
install:
  - python setup.py install
script:
  - python test.py
notifications:
    email: false
